version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dotnetwebapi
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
      
  dotnetwebapi:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysql
      - mongodb
    environment:
      DbServer: "mysql"
      DbPort: "3306"
      DbUser: "root"
      Password: "root"
      Database: "dotnetwebapi"
    ports: 
      - "8080:80"
