version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
      
  dotnetwebapi:
    build: .
    depends_on:
      - ms-sql-server
    environment:
      DbServer: "mysql"
      DbPort: "33060"
      DbUser: "root"
      Password: "root"
      Database: "bookDb"
    ports: 
      - "8080:80"
